## STANDARD RULES VALUES
developmentCards:
  - developmentCardID: DEV_G1
    level: 1
    colour: GREEN
    production: PROD_DEV_G1    # 1 COINS --> 1 FAITH POINT
    victoryPoints: 1
    purchaseCost:
      SHIELDS: 2
  - developmentCardID: DEV_G2
    level: 1
    colour: GREEN
    production: PROD_DEV_G2    # 1 STONES --> 1 SERVANTS
    victoryPoints: 2
    purchaseCost:
      SHIELDS: 1
      SERVANTS: 1
      STONES: 1
  - developmentCardID: DEV_G3
    level: 1
    colour: GREEN
    production: PROD_DEV_G3    # 2 SERVANTS --> 1 COINS, 1 SHIELDS, 1 STONES
    victoryPoints: 3
    purchaseCost:
      SHIELDS: 3
  - developmentCardID: DEV_G4
    level: 1
    colour: GREEN
    production: PROD_DEV_G4    # 1 STONES, 1 SERVANTS --> 2 COINS, 1 FAITH POINT
    victoryPoints: 4
    purchaseCost:
      SHIELDS: 2
      COINS: 2
  - developmentCardID: DEV_G5
    level: 2
    colour: GREEN
    production: PROD_DEV_G5    # 1 STONES --> 2 FAITH POINTS
    victoryPoints: 5
    purchaseCost:
      SHIELDS: 4
  - developmentCardID: DEV_G6
    level: 2
    colour: GREEN
    production: PROD_DEV_G6    # 1 SHIELDS, 1 SERVANTS --> 3 STONES
    victoryPoints: 6
    purchaseCost:
      SHIELDS: 3
      SERVANTS: 2
  - developmentCardID: DEV_G7
    level: 2
    colour: GREEN
    production: PROD_DEV_G7    # 2 COINS --> 2 STONES, 2 FAITH POINTS
    victoryPoints: 7
    purchaseCost:
      SHIELDS: 5
  - developmentCardID: DEV_G8
    level: 2
    colour: GREEN
    production: PROD_DEV_G8    # 1 COINS --> 2 SHIELDS, 1 FAITH POINTS
    victoryPoints: 8
    purchaseCost:
      SHIELDS: 3
      COINS: 3
  - developmentCardID: DEV_G9
    level: 3
    colour: GREEN
    production: PROD_DEV_G9    # 2 SERVANTS --> 3 STONES, 2 FAITH POINTS
    victoryPoints: 9
    purchaseCost:
      SHIELDS: 6
  - developmentCardID: DEV_G10
    level: 3
    colour: GREEN
    production: PROD_DEV_G10    # 1 COINS, 1 SERVANTS --> 2 SHIELDS, 2 STONES, 1 FAITH POINT
    victoryPoints: 10
    purchaseCost:
      SHIELDS: 5
      SERVANTS: 2
  - developmentCardID: DEV_G11
    level: 3
    colour: GREEN
    production: PROD_DEV_11    # 1 SERVANTS --> 1 COINS, 3 FAITH POINTS
    victoryPoints: 11
    purchaseCost:
      SHIELDS: 7
  - developmentCardID: DEV_G12
    level: 3
    colour: GREEN
    production: PROD_DEV_G12    # 1 STONES --> 3 COINS, 1 SHIELDS
    victoryPoints: 12
    purchaseCost:
      SHIELDS: 4
      COINS: 4
  - developmentCardID: DEV_Y1
    level: 1
    colour: YELLOW
    production: PROD_DEV_Y1    # 1 SERVANTS --> 1 FAITH POINT
    victoryPoints: 1
    purchaseCost:
      STONES: 2
  - developmentCardID: DEV_Y2
    level: 1
    colour: YELLOW
    production: PROD_DEV_Y2    # 1 SHIELDS --> 1 COINS
    victoryPoints: 2
    purchaseCost:
      SHIELDS: 1
      STONES: 1
      COINS: 1
  - developmentCardID: DEV_Y3
    level: 1
    colour: YELLOW
    production: PROD_DEV_Y3    # 2 SHIELDS --> 1 COINS, 1 SERVANTS, 1 STONES
    victoryPoints: 3
    purchaseCost:
      STONES: 3
  - developmentCardID: DEV_Y4
    level: 1
    colour: YELLOW
    production: PROD_DEV_Y4    # 1 COINS, 1 SERVANTS --> 2 SHIELDS, 1 FAITH POINT
    victoryPoints: 4
    purchaseCost:
      STONES: 2
      SHIELDS: 2
  - developmentCardID: DEV_Y5
    level: 2
    colour: YELLOW
    production: PROD_DEV_Y5    # 1 SHIELDS --> 2 FAITH POINTS
    victoryPoints: 5
    purchaseCost:
      STONES: 4
  - developmentCardID: DEV_Y6
    level: 2
    colour: YELLOW
    production: PROD_DEV_Y6    # 1 STONES, 1 SHIELDS --> 3 COINS
    victoryPoints: 6
    purchaseCost:
      STONES: 3
      SHIELDS: 2
  - developmentCardID: DEV_Y7
    level: 2
    colour: YELLOW
    production: PROD_DEV_Y7    # 2 SHIELDS --> 2 SERVANTS, 2 FAITH POINTS
    victoryPoints: 7
    purchaseCost:
      STONES: 5
  - developmentCardID: DEV_Y8
    level: 2
    colour: YELLOW
    production: PROD_DEV_Y8    # 1 SHIELDS --> 2 COINS, 1 FAITH POINTS
    victoryPoints: 8
    purchaseCost:
      STONES: 3
      SERVANTS: 3
  - developmentCardID: DEV_Y9
    level: 3
    colour: YELLOW
    production: PROD_DEV_Y9    # 2 SHIELDS --> 3 SERVANTS, 2 FAITH POINTS
    victoryPoints: 9
    purchaseCost:
      STONES: 6
  - developmentCardID: DEV_Y10
    level: 3
    colour: YELLOW
    production: PROD_DEV_Y10    # 1 STONES, 1 SERVANTS --> 2 COINS, 2 SHIELDS, 1 FAITH POINT
    victoryPoints: 10
    purchaseCost:
      STONES: 5
      SERVANTS: 2
  - developmentCardID: DEV_Y11
    level: 3
    colour: YELLOW
    production: PROD_DEV_Y11    # 1 SHIELDS --> 1 SERVANTS, 3 FAITH POINTS
    victoryPoints: 11
    purchaseCost:
      STONES: 7
  - developmentCardID: DEV_Y12
    level: 3
    colour: YELLOW
    production: PROD_DEV_Y12    # 1 SHIELDS --> 1 STONES, 3 SERVANTS
    victoryPoints: 12
    purchaseCost:
      STONES: 4
      SERVANTS: 4
  - developmentCardID: DEV_B1
    level: 1
    colour: BLUE
    production: PROD_DEV_B1    # 1 SHIELDS --> 1 FAITH POINT
    victoryPoints: 1
    purchaseCost:
      COINS: 2
  - developmentCardID: DEV_B2
    level: 1
    colour: BLUE
    production: PROD_DEV_B2    # 1 SERVANTS --> 1 STONES
    victoryPoints: 2
    purchaseCost:
      COINS: 1
      SERVANTS: 1
      STONES: 1
  - developmentCardID: DEV_B3
    level: 1
    colour: BLUE
    production: PROD_DEV_B3    # 2 STONES --> 1 COINS, 1 SERVANTS, 1 SHIELDS
    victoryPoints: 3
    purchaseCost:
      COINS: 3
  - developmentCardID: DEV_B4
    level: 1
    colour: BLUE
    production: PROD_DEV_B4    # 1 SHIELDS, 1 STONES --> 2 SERVANTS, 1 FAITH POINT
    victoryPoints: 4
    purchaseCost:
      COINS: 2
      SERVANTS: 2
  - developmentCardID: DEV_B5
    level: 2
    colour: BLUE
    production: PROD_DEV_B5    # 1 SERVANTS --> 2 FAITH POINTS
    victoryPoints: 5
    purchaseCost:
      COINS: 4
  - developmentCardID: DEV_B6
    level: 2
    colour: BLUE
    production: PROD_DEV_B6    # 1 COINS, 1 STONES --> 3 SERVANTS
    victoryPoints: 6
    purchaseCost:
      COINS: 3
      STONES: 2
  - developmentCardID: DEV_B7
    level: 2
    colour: BLUE
    production: PROD_DEV_B7    # 2 SERVANTS --> 2 SHIELDS, 2 FAITH POINTS
    victoryPoints: 7
    purchaseCost:
      COINS: 5
  - developmentCardID: DEV_B8
    level: 2
    colour: BLUE
    production: PROD_DEV_B8    # 1 SERVANTS --> 2 STONES, 1 FAITH POINTS
    victoryPoints: 8
    purchaseCost:
      COINS: 3
      STONES: 3
  - developmentCardID: DEV_B9
    level: 3
    colour: BLUE
    production: PROD_DEV_B9    # 2 SERVANTS --> 3 SHIELDS, 2 FAITH POINTS
    victoryPoints: 9
    purchaseCost:
      COINS: 6
  - developmentCardID: DEV_B10
    level: 3
    colour: BLUE
    production: PROD_DEV_B10    # 1 COINS, 1 SHIELDS --> 2 SERVANTS, 2 STONES, 1 FAITH POINT
    victoryPoints: 10
    purchaseCost:
      COINS: 5
      STONES: 2
  - developmentCardID: DEV_B11
    level: 3
    colour: BLUE
    production: PROD_DEV_B11    # 1 STONES --> 1 SHIELDS, 3 FAITH POINTS
    victoryPoints: 11
    purchaseCost:
      COINS: 7
  - developmentCardID: DEV_B12
    level: 3
    colour: BLUE
    production: PROD_DEV_B12    # 1 SERVANTS --> 1 COINS, 3 SHIELDS
    victoryPoints: 12
    purchaseCost:
      COINS: 4
      STONES: 4
  - developmentCardID: DEV_P1
    level: 1
    colour: PURPLE
    production: PROD_DEV_P1    # 1 STONES --> 1 FAITH POINT
    victoryPoints: 1
    purchaseCost:
      SERVANTS: 2
  - developmentCardID: DEV_P2
    level: 1
    colour: PURPLE
    production: PROD_DEV_P2    # 1 COINS --> 1 SHIELDS
    victoryPoints: 2
    purchaseCost:
      SHIELDS: 1
      SERVANTS: 1
      COINS: 1
  - developmentCardID: DEV_P3
    level: 1
    colour: PURPLE
    production: PROD_DEV_P3    # 2 COINS --> 1 SERVANTS, 1 SHIELDS, 1 STONES
    victoryPoints: 3
    purchaseCost:
      SERVANTS: 3
  - developmentCardID: DEV_P4
    level: 1
    colour: PURPLE
    production: PROD_DEV_P4    # 1 COINS, 1 SHIELDS --> 2 STONES, 1 FAITH POINT
    victoryPoints: 4
    purchaseCost:
      SERVANTS: 2
      STONES: 2
  - developmentCardID: DEV_P5
    level: 2
    colour: PURPLE
    production: PROD_DEV_P5    # 1 COINS --> 2 FAITH POINTS
    victoryPoints: 5
    purchaseCost:
      SERVANTS: 4
  - developmentCardID: DEV_P6
    level: 2
    colour: PURPLE
    production: PROD_DEV_P6    # 1 COINS, 1 SERVANTS --> 3 SHIELDS
    victoryPoints: 6
    purchaseCost:
      SERVANTS: 3
      COINS: 2
  - developmentCardID: DEV_P7
    level: 2
    colour: PURPLE
    production: PROD_DEV_P7    # 2 STONES --> 2 COINS, 2 FAITH POINTS
    victoryPoints: 7
    purchaseCost:
      SERVANTS: 5
  - developmentCardID: DEV_P8
    level: 2
    colour: PURPLE
    production: PROD_DEV_P8    # 1 STONES --> 2 SERVANTS, 1 FAITH POINTS
    victoryPoints: 8
    purchaseCost:
      SERVANTS: 3
      SHIELDS: 3
  - developmentCardID: DEV_P9
    level: 3
    colour: PURPLE
    production: PROD_DEV_P9    # 2 STONES --> 3 COINS, 2 FAITH POINTS
    victoryPoints: 9
    purchaseCost:
      SERVANTS: 6
  - developmentCardID: DEV_P10
    level: 3
    colour: PURPLE
    production: PROD_DEV_P10    # 1 STONES, 1 SHIELDS --> 2 COINS, 2 SERVANTS, 1 FAITH POINT
    victoryPoints: 10
    purchaseCost:
      SERVANTS: 5
      COINS: 2
  - developmentCardID: DEV_P11
    level: 3
    colour: PURPLE
    production: PROD_DEV_P11    # 1 COINS --> 1 STONES, 3 FAITH POINTS
    victoryPoints: 11
    purchaseCost:
      SERVANTS: 7
  - developmentCardID: DEV_P12
    level: 3
    colour: PURPLE
    production: PROD_DEV_P12    # 1 COINS --> 3 STONES, 1 SERVANTS
    victoryPoints: 12
    purchaseCost:
      SERVANTS: 4
      SHIELDS: 4