## STANDARD RULES VALUES
leaderCards:
  - leaderCardID: LEADER_DISC_1
    requirements:
      - requirementType: COLOUR
        cardColour: YELLOW
        numberOfCards: 1
      - requirementType: COLOUR
        cardColour: PURPLE
        numberOfCards: 1
    developmentCardCostDiscounts:
      - DISCOUNT_1      #  1 COINS
    victoryPoints: 2
  - leaderCardID: LEADER_DISC_2
    requirements:
      - requirementType: COLOUR
        cardColour: GREEN
        numberOfCards: 1
      - requirementType: COLOUR
        cardColour: BLUE
        numberOfCards: 1
    developmentCardCostDiscounts:
      - DISCOUNT_2      #  1 STONES
    victoryPoints: 2
  - leaderCardID: LEADER_DISC_3
    requirements:
      - requirementType: COLOUR
        cardColour: BLUE
        numberOfCards: 1
      - requirementType: COLOUR
        cardColour: PURPLE
        numberOfCards: 1
    developmentCardCostDiscounts:
      - DISCOUNT_3      #  1 SHIELDS
    victoryPoints: 2
  - leaderCardID: LEADER_DISC_4
    requirements:
      - requirementType: COLOUR
        cardColour: YELLOW
        numberOfCards: 1
      - requirementType: COLOUR
        cardColour: GREEN
        numberOfCards: 1
    developmentCardCostDiscounts:
      - DISCOUNT_4      #  1 SERVANTS
    victoryPoints: 2
  - leaderCardID: LEADER_STOR_1
    requirements:
      - requirementType: RESOURCE
        resourceType: SHIELDS
        numberOfResources: 5
    resourceStorages:
      - STORAGE_1       # 1 COINS
      - STORAGE_2       # 1 COINS
    victoryPoints: 3
  - leaderCardID: LEADER_STOR_2
    requirements:
      - requirementType: RESOURCE
        resourceType: SERVANTS
        numberOfResources: 5
    resourceStorages:
      - STORAGE_3       # 1 SHIELDS
      - STORAGE_4       # 1 SHIELDS
    victoryPoints: 3
  - leaderCardID: LEADER_STOR_3
    requirements:
      - requirementType: RESOURCE
        resourceType: STONES
        numberOfResources: 5
    resourceStorages:
      - STORAGE_5       # 1 SERVANTS
      - STORAGE_6       # 1 SERVANTS
    victoryPoints: 3
  - leaderCardID: LEADER_STOR_4
    requirements:
      - requirementType: RESOURCE
        resourceType: COINS
        numberOfResources: 5
    resourceStorages:
      - STORAGE_7       # 1 STONES
      - STORAGE_8       # 1 STONES
    victoryPoints: 3
  - leaderCardID: LEADER_PROD_1
    requirements:
      - requirementType: COLOUR_AND_LEVEL
        cardColour: YELLOW
        cardLevel: 2
        numberOfCards: 1
    productions:
      - PROD_LEAD_1      # 1 SHIELDS --> 1 STAR, 1 FAITH POINT
    victoryPoints: 4
  - leaderCardID: LEADER_PROD_2
    requirements:
      - requirementType: COLOUR_AND_LEVEL
        cardColour: GREEN
        cardLevel: 2
        numberOfCards: 1
    productions:
      - PROD_LEAD_2      # 1 COINS --> 1 STAR, 1 FAITH POINT
    victoryPoints: 4
  - leaderCardID: LEADER_PROD_3
    requirements:
      - requirementType: COLOUR_AND_LEVEL
        cardColour: PURPLE
        cardLevel: 2
        numberOfCards: 1
    productions:
      - PROD_LEAD_3      # 1 STONES --> 1 STAR, 1 FAITH POINT
    victoryPoints: 4
  - leaderCardID: LEADER_PROD_4
    requirements:
      - requirementType: COLOUR_AND_LEVEL
        cardColour: BLUE
        cardLevel: 2
        numberOfCards: 1
    productions:
      - PROD_LEAD_4      # 1 SERVANTS --> 1 STAR, 1 FAITH POINT
    victoryPoints: 4
  - leaderCardID: LEADER_SUB_1
    requirements:
      - requirementType: COLOUR
        cardColour: YELLOW
        numberOfCards: 2
      - requirementType: COLOUR
        cardColour: BLUE
        numberOfCards: 1
    specialMarbleSubstitutions:
      - SUB_SERVANT       # 1 SERVANTS
    victoryPoints: 5
  - leaderCardID: LEADER_SUB_2
    requirements:
      - requirementType: COLOUR
        cardColour: PURPLE
        numberOfCards: 2
      - requirementType: COLOUR
        cardColour: GREEN
        numberOfCards: 1
    specialMarbleSubstitutions:
      - SUB_COIN       # 1 COINS
    victoryPoints: 5
  - leaderCardID: LEADER_SUB_3
    requirements:
      - requirementType: COLOUR
        cardColour: BLUE
        numberOfCards: 2
      - requirementType: COLOUR
        cardColour: YELLOW
        numberOfCards: 1
    specialMarbleSubstitutions:
      - SUB_STONE       # 1 STONES
    victoryPoints: 5
  - leaderCardID: LEADER_SUB_4
    requirements:
      - requirementType: COLOUR
        cardColour: GREEN
        numberOfCards: 2
      - requirementType: COLOUR
        cardColour: PURPLE
        numberOfCards: 1
    specialMarbleSubstitutions:
      - SUB_SHIELD       # 1 SHIELDS
    victoryPoints: 5