## STANDARD RULES VALUES
leaderCards:
  - leaderCardID: LEADER_DISC_1
    requirements:
      - requirementType: COLOUR
        cardColour: YELLOW
        numberOfCards: 1
      - requirementType: COLOUR
        cardColour: PURPLE
        numberOfCards: 1
    developmentCardCostDiscounts:
      - resourceType: COINS
        amountToDiscount: 1
    victoryPoints: 2
  - leaderCardID: LEADER_DISC_2
    requirements:
      - requirementType: COLOUR
        cardColour: GREEN
        numberOfCards: 1
      - requirementType: COLOUR
        cardColour: BLUE
        numberOfCards: 1
    developmentCardCostDiscounts:
      - resourceType: STONES
        amountToDiscount: 1
    victoryPoints: 2
  - leaderCardID: LEADER_DISC_3
    requirements:
      - requirementType: COLOUR
        cardColour: BLUE
        numberOfCards: 1
      - requirementType: COLOUR
        cardColour: PURPLE
        numberOfCards: 1
    developmentCardCostDiscounts:
      - resourceType: SHIELDS
        amountToDiscount: 1
    victoryPoints: 2
  - leaderCardID: LEADER_DISC_4
    requirements:
      - requirementType: COLOUR
        cardColour: YELLOW
        numberOfCards: 1
      - requirementType: COLOUR
        cardColour: GREEN
        numberOfCards: 1
    developmentCardCostDiscounts:
      - resourceType: SERVANTS
        amountToDiscount: 1
    victoryPoints: 2
  - leaderCardID: LEADER_STOR_1
    requirements:
      - requirementType: RESOURCE
        resourceType: SHIELDS
        numberOfResources: 5
    resourceStorages:
      - storage:
          rules:
            - ruleType: MAX_RESOURCE_NUMBER
              maxNumber: 2
            - ruleType: SPECIFIC_RESOURCE_TYPE
              resourceType: COINS
    victoryPoints: 3
  - leaderCardID: LEADER_STOR_2
    requirements:
      - requirementType: RESOURCE
        resourceType: SERVANTS
        numberOfResources: 5
    resourceStorages:
      - storage:
          rules:
            - ruleType: MAX_RESOURCE_NUMBER
              maxNumber: 2
            - ruleType: SPECIFIC_RESOURCE_TYPE
              resourceType: SHIELDS
    victoryPoints: 3
  - leaderCardID: LEADER_STOR_3
    requirements:
      - requirementType: RESOURCE
        resourceType: STONES
        numberOfResources: 5
    resourceStorages:
      - storage:
          rules:
            - ruleType: MAX_RESOURCE_NUMBER
              maxNumber: 2
            - ruleType: SPECIFIC_RESOURCE_TYPE
              resourceType: SERVANTS
    victoryPoints: 3
  - leaderCardID: LEADER_STOR_4
    requirements:
      - requirementType: RESOURCE
        resourceType: COINS
        numberOfResources: 5
    resourceStorages:
      - storage:
          rules:
            - ruleType: MAX_RESOURCE_NUMBER
              maxNumber: 2
            - ruleType: SPECIFIC_RESOURCE_TYPE
              resourceType: STONES
    victoryPoints: 3
  - leaderCardID: LEADER_PROD_1
    requirements:
      - requirementType: COLOUR_AND_LEVEL
        cardColour: YELLOW
        cardLevel: 2
        numberOfCards: 1
    productions:
      - costs:
          resources:
            SHIELDS: 1
          starResources: 0
        rewards:
          resources: {}
          starResources: 1
          faithPoints: 1
    victoryPoints: 4
  - leaderCardID: LEADER_PROD_2
    requirements:
      - requirementType: COLOUR_AND_LEVEL
        cardColour: GREEN
        cardLevel: 2
        numberOfCards: 1
    productions:
      - costs:
          resources:
            COINS: 1
          starResources: 0
        rewards:
          resources: {}
          starResources: 1
          faithPoints: 1
    victoryPoints: 4
  - leaderCardID: LEADER_PROD_3
    requirements:
      - requirementType: COLOUR_AND_LEVEL
        cardColour: PURPLE
        cardLevel: 2
        numberOfCards: 1
    productions:
      - costs:
          resources:
            STONES: 1
          starResources: 0
        rewards:
          resources: { }
          starResources: 1
          faithPoints: 1
    victoryPoints: 4
  - leaderCardID: LEADER_PROD_4
    requirements:
      - requirementType: COLOUR_AND_LEVEL
        cardColour: BLUE
        cardLevel: 2
        numberOfCards: 1
    productions:
      - costs:
          resources:
            SERVANTS: 1
          starResources: 0
        rewards:
          resources: { }
          starResources: 1
          faithPoints: 1
    victoryPoints: 4
  - leaderCardID: LEADER_SUB_1
    requirements:
      - requirementType: COLOUR
        cardColour: YELLOW
        numberOfCards: 2
      - requirementType: COLOUR
        cardColour: BLUE
        numberOfCards: 1
    specialMarbleSubstitutions:
      - resourceType: SERVANTS
    victoryPoints: 5
  - leaderCardID: LEADER_SUB_2
    requirements:
      - requirementType: COLOUR
        cardColour: PURPLE
        numberOfCards: 2
      - requirementType: COLOUR
        cardColour: GREEN
        numberOfCards: 1
    specialMarbleSubstitutions:
      - resourceType: COINS
    victoryPoints: 5
  - leaderCardID: LEADER_SUB_3
    requirements:
      - requirementType: COLOUR
        cardColour: BLUE
        numberOfCards: 2
      - requirementType: COLOUR
        cardColour: YELLOW
        numberOfCards: 1
    specialMarbleSubstitutions:
      - resourceType: STONES
    victoryPoints: 5
  - leaderCardID: LEADER_SUB_4
    requirements:
      - requirementType: COLOUR
        cardColour: GREEN
        numberOfCards: 2
      - requirementType: COLOUR
        cardColour: PURPLE
        numberOfCards: 1
    specialMarbleSubstitutions:
      - resourceType: SHIELDS
    victoryPoints: 5