# STANDARD RULES VALUES #F

## DEVELOPMENT CARDS CONFIGURATION FILE ##
# This file sets all the parameters regarding the Development Cards in the Game (48 Cards in the standard Game).

# Each Development Card is identified by:
#  - unique ID
#  - fixed level (according to the standard Game rules, a number between 1 and 3)
#  - colour (according to the standard Game rules, a colour between GREEN, YELLOW, BLUE and PURPLE)
#  - Production powers (the Player can pay the following costs to obtain the specified rewards), each characterized by:
#    - costs:
#      - cost made of specific type and number of Resources
#      - cost made of a generic type of Resource (Player can choose), in a fixed quantity
#    - rewards:
#      - reward made of specific type and number of Resources
#      - reward made of a generic type of Resource (Player can choose), in a fixed quantity
#      - reward made of a fixed number of Faith Points
#  - number of Victory Points given at the end of the Game to the Player who owns this Development Card
#  - purchase cost, necessary to allow the Player to buy this Development Card (specific Resources in a fixed quantity)
developmentCards:
  - developmentCardID: DEV_G1
    level: 1
    colour: GREEN
    productions:
      - costs:
          resources:
            COINS: 1
          starResources: 0
        rewards:
          resources: {}
          starResources: 0
          faithPoints: 1
    victoryPoints: 1
    purchaseCost:
      SHIELDS: 2
  - developmentCardID: DEV_G2
    level: 1
    colour: GREEN
    productions:
      - costs:
          resources:
            STONES: 1
          starResources: 0
        rewards:
          resources:
            SERVANTS: 1
          starResources: 0
          faithPoints: 0
    victoryPoints: 2
    purchaseCost:
      SHIELDS: 1
      SERVANTS: 1
      STONES: 1
  - developmentCardID: DEV_G3
    level: 1
    colour: GREEN
    productions:
      - costs:
          resources:
            SERVANTS: 2
          starResources: 0
        rewards:
          resources:
            COINS: 1
            SHIELDS: 1
            STONES: 1
          starResources: 0
          faithPoints: 0
    victoryPoints: 3
    purchaseCost:
      SHIELDS: 3
  - developmentCardID: DEV_G4
    level: 1
    colour: GREEN
    productions:
      - costs:
          resources:
            STONES: 1
            SERVANTS: 1
          starResources: 0
        rewards:
          resources:
            COINS: 2
          starResources: 0
          faithPoints: 1
    victoryPoints: 4
    purchaseCost:
      SHIELDS: 2
      COINS: 2
  - developmentCardID: DEV_G5
    level: 2
    colour: GREEN
    productions:
      - costs:
          resources:
            STONES: 1
          starResources: 0
        rewards:
          resources: {}
          starResources: 0
          faithPoints: 2
    victoryPoints: 5
    purchaseCost:
      SHIELDS: 4
  - developmentCardID: DEV_G6
    level: 2
    colour: GREEN
    productions:
      - costs:
          resources:
            SHIELDS: 1
            SERVANTS: 1
          starResources: 0
        rewards:
          resources:
            STONES: 3
          starResources: 0
          faithPoints: 0
    victoryPoints: 6
    purchaseCost:
      SHIELDS: 3
      SERVANTS: 2
  - developmentCardID: DEV_G7
    level: 2
    colour: GREEN
    productions:
      - costs:
          resources:
            COINS: 2
          starResources: 0
        rewards:
          resources:
            STONES: 2
          starResources: 0
          faithPoints: 2
    victoryPoints: 7
    purchaseCost:
      SHIELDS: 5
  - developmentCardID: DEV_G8
    level: 2
    colour: GREEN
    productions:
      - costs:
          resources:
            COINS: 1
          starResources: 0
        rewards:
          resources:
            SHIELDS: 2
          starResources: 0
          faithPoints: 1
    victoryPoints: 8
    purchaseCost:
      SHIELDS: 3
      COINS: 3
  - developmentCardID: DEV_G9
    level: 3
    colour: GREEN
    productions:
      - costs:
          resources:
            SERVANTS: 2
          starResources: 0
        rewards:
          resources:
            STONES: 3
          starResources: 0
          faithPoints: 2
    victoryPoints: 9
    purchaseCost:
      SHIELDS: 6
  - developmentCardID: DEV_G10
    level: 3
    colour: GREEN
    productions:
      - costs:
          resources:
            COINS: 1
            SERVANTS: 1
          starResources: 0
        rewards:
          resources:
            SHIELDS: 2
            STONES: 2
          starResources: 0
          faithPoints: 1
    victoryPoints: 10
    purchaseCost:
      SHIELDS: 5
      SERVANTS: 2
  - developmentCardID: DEV_G11
    level: 3
    colour: GREEN
    productions:
      - costs:
          resources:
            SERVANTS: 1
          starResources: 0
        rewards:
          resources:
            COINS: 1
          starResources: 0
          faithPoints: 3
    victoryPoints: 11
    purchaseCost:
      SHIELDS: 7
  - developmentCardID: DEV_G12
    level: 3
    colour: GREEN
    productions:
      - costs:
          resources:
            STONES: 1
          starResources: 0
        rewards:
          resources:
            COINS: 3
            SHIELDS: 1
          starResources: 0
          faithPoints: 0
    victoryPoints: 12
    purchaseCost:
      SHIELDS: 4
      COINS: 4
  - developmentCardID: DEV_Y1
    level: 1
    colour: YELLOW
    productions:
      - costs:
          resources:
            SERVANTS: 1
          starResources: 0
        rewards:
          resources: {}
          starResources: 0
          faithPoints: 1
    victoryPoints: 1
    purchaseCost:
      STONES: 2
  - developmentCardID: DEV_Y2
    level: 1
    colour: YELLOW
    productions:
      - costs:
          resources:
            SHIELDS: 1
          starResources: 0
        rewards:
          resources:
            COINS: 1
          starResources: 0
          faithPoints: 0
    victoryPoints: 2
    purchaseCost:
      SHIELDS: 1
      STONES: 1
      COINS: 1
  - developmentCardID: DEV_Y3
    level: 1
    colour: YELLOW
    productions:
      - costs:
          resources:
            SHIELDS: 2
          starResources: 0
        rewards:
          resources:
            COINS: 1
            SERVANTS: 1
            STONES: 1
          starResources: 0
          faithPoints: 0
    victoryPoints: 3
    purchaseCost:
      STONES: 3
  - developmentCardID: DEV_Y4
    level: 1
    colour: YELLOW
    productions:
      - costs:
          resources:
            COINS: 1
            SERVANTS: 1
          starResources: 0
        rewards:
          resources:
            SHIELDS: 2
          starResources: 0
          faithPoints: 1
    victoryPoints: 4
    purchaseCost:
      STONES: 2
      SHIELDS: 2
  - developmentCardID: DEV_Y5
    level: 2
    colour: YELLOW
    productions:
      - costs:
          resources:
            SHIELDS: 1
          starResources: 0
        rewards:
          resources: { }
          starResources: 0
          faithPoints: 2
    victoryPoints: 5
    purchaseCost:
      STONES: 4
  - developmentCardID: DEV_Y6
    level: 2
    colour: YELLOW
    productions:
      - costs:
          resources:
            STONES: 1
            SHIELDS: 1
          starResources: 0
        rewards:
          resources:
            COINS: 3
          starResources: 0
          faithPoints: 0
    victoryPoints: 6
    purchaseCost:
      STONES: 3
      SHIELDS: 2
  - developmentCardID: DEV_Y7
    level: 2
    colour: YELLOW
    productions:
      - costs:
          resources:
            SHIELDS: 2
          starResources: 0
        rewards:
          resources:
            SERVANTS: 2
          starResources: 0
          faithPoints: 2
    victoryPoints: 7
    purchaseCost:
      STONES: 5
  - developmentCardID: DEV_Y8
    level: 2
    colour: YELLOW
    productions:
      - costs:
          resources:
            SHIELDS: 1
          starResources: 0
        rewards:
          resources:
            COINS: 2
          starResources: 0
          faithPoints: 1
    victoryPoints: 8
    purchaseCost:
      STONES: 3
      SERVANTS: 3
  - developmentCardID: DEV_Y9
    level: 3
    colour: YELLOW
    productions:
      - costs:
          resources:
            SHIELDS: 2
          starResources: 0
        rewards:
          resources:
            SERVANTS: 3
          starResources: 0
          faithPoints: 2
    victoryPoints: 9
    purchaseCost:
      STONES: 6
  - developmentCardID: DEV_Y10
    level: 3
    colour: YELLOW
    productions:
      - costs:
          resources:
            STONES: 1
            SERVANTS: 1
          starResources: 0
        rewards:
          resources:
            COINS: 2
            SHIELDS: 2
          starResources: 0
          faithPoints: 1
    victoryPoints: 10
    purchaseCost:
      STONES: 5
      SERVANTS: 2
  - developmentCardID: DEV_Y11
    level: 3
    colour: YELLOW
    productions:
      - costs:
          resources:
            SHIELDS: 1
          starResources: 0
        rewards:
          resources:
            SERVANTS: 1
          starResources: 0
          faithPoints: 3
    victoryPoints: 11
    purchaseCost:
      STONES: 7
  - developmentCardID: DEV_Y12
    level: 3
    colour: YELLOW
    productions:
      - costs:
          resources:
            SHIELDS: 1
          starResources: 0
        rewards:
          resources:
            STONES: 1
            SERVANTS: 3
          starResources: 0
          faithPoints: 0
    victoryPoints: 12
    purchaseCost:
      STONES: 4
      SERVANTS: 4
  - developmentCardID: DEV_B1
    level: 1
    colour: BLUE
    productions:
      - costs:
          resources:
            SHIELDS: 1
          starResources: 0
        rewards:
          resources: { }
          starResources: 0
          faithPoints: 1
    victoryPoints: 1
    purchaseCost:
      COINS: 2
  - developmentCardID: DEV_B2
    level: 1
    colour: BLUE
    productions:
      - costs:
          resources:
            SERVANTS: 1
          starResources: 0
        rewards:
          resources:
            STONES: 1
          starResources: 0
          faithPoints: 0
    victoryPoints: 2
    purchaseCost:
      COINS: 1
      SERVANTS: 1
      STONES: 1
  - developmentCardID: DEV_B3
    level: 1
    colour: BLUE
    productions:
      - costs:
          resources:
            STONES: 2
          starResources: 0
        rewards:
          resources:
            COINS: 1
            SERVANTS: 1
            SHIELDS: 1
          starResources: 0
          faithPoints: 0
    victoryPoints: 3
    purchaseCost:
      COINS: 3
  - developmentCardID: DEV_B4
    level: 1
    colour: BLUE
    productions:
      - costs:
          resources:
            SHIELDS: 1
            STONES: 1
          starResources: 0
        rewards:
          resources:
            SERVANTS: 2
          starResources: 0
          faithPoints: 1
    victoryPoints: 4
    purchaseCost:
      COINS: 2
      SERVANTS: 2
  - developmentCardID: DEV_B5
    level: 2
    colour: BLUE
    productions:
      - costs:
          resources:
            SERVANTS: 1
          starResources: 0
        rewards:
          resources: { }
          starResources: 0
          faithPoints: 2
    victoryPoints: 5
    purchaseCost:
      COINS: 4
  - developmentCardID: DEV_B6
    level: 2
    colour: BLUE
    productions:
      - costs:
          resources:
            COINS: 1
            STONES: 1
          starResources: 0
        rewards:
          resources:
            SERVANTS: 3
          starResources: 0
          faithPoints: 0
    victoryPoints: 6
    purchaseCost:
      COINS: 3
      STONES: 2
  - developmentCardID: DEV_B7
    level: 2
    colour: BLUE
    productions:
      - costs:
          resources:
            SERVANTS: 2
          starResources: 0
        rewards:
          resources:
            SHIELDS: 2
          starResources: 0
          faithPoints: 2
    victoryPoints: 7
    purchaseCost:
      COINS: 5
  - developmentCardID: DEV_B8
    level: 2
    colour: BLUE
    productions:
      - costs:
          resources:
            SERVANTS: 1
          starResources: 0
        rewards:
          resources:
            STONES: 2
          starResources: 0
          faithPoints: 1
    victoryPoints: 8
    purchaseCost:
      COINS: 3
      STONES: 3
  - developmentCardID: DEV_B9
    level: 3
    colour: BLUE
    productions:
      - costs:
          resources:
            SERVANTS: 2
          starResources: 0
        rewards:
          resources:
            SHIELDS: 3
          starResources: 0
          faithPoints: 2
    victoryPoints: 9
    purchaseCost:
      COINS: 6
  - developmentCardID: DEV_B10
    level: 3
    colour: BLUE
    productions:
      - costs:
          resources:
            COINS: 1
            SHIELDS: 1
          starResources: 0
        rewards:
          resources:
            SERVANTS: 2
            STONES: 2
          starResources: 0
          faithPoints: 1
    victoryPoints: 10
    purchaseCost:
      COINS: 5
      STONES: 2
  - developmentCardID: DEV_B11
    level: 3
    colour: BLUE
    productions:
      - costs:
          resources:
            STONES: 1
          starResources: 0
        rewards:
          resources:
            SHIELDS: 1
          starResources: 0
          faithPoints: 3
    victoryPoints: 11
    purchaseCost:
      COINS: 7
  - developmentCardID: DEV_B12
    level: 3
    colour: BLUE
    productions:
      - costs:
          resources:
            SERVANTS: 1
          starResources: 0
        rewards:
          resources:
            COINS: 1
            SHIELDS: 3
          starResources: 0
          faithPoints: 0
    victoryPoints: 12
    purchaseCost:
      COINS: 4
      STONES: 4
  - developmentCardID: DEV_P1
    level: 1
    colour: PURPLE
    productions:
      - costs:
          resources:
            STONES: 1
          starResources: 0
        rewards:
          resources: { }
          starResources: 0
          faithPoints: 1
    victoryPoints: 1
    purchaseCost:
      SERVANTS: 2
  - developmentCardID: DEV_P2
    level: 1
    colour: PURPLE
    productions:
      - costs:
          resources:
            COINS: 1
          starResources: 0
        rewards:
          resources:
            SHIELDS: 1
          starResources: 0
          faithPoints: 0
    victoryPoints: 2
    purchaseCost:
      SHIELDS: 1
      SERVANTS: 1
      COINS: 1
  - developmentCardID: DEV_P3
    level: 1
    colour: PURPLE
    productions:
      - costs:
          resources:
            COINS: 2
          starResources: 0
        rewards:
          resources:
            SERVANTS: 1
            SHIELDS: 1
            STONES: 1
          starResources: 0
          faithPoints: 0
    victoryPoints: 3
    purchaseCost:
      SERVANTS: 3
  - developmentCardID: DEV_P4
    level: 1
    colour: PURPLE
    productions:
      - costs:
          resources:
            COINS: 1
            SHIELDS: 1
          starResources: 0
        rewards:
          resources:
            STONES: 2
          starResources: 0
          faithPoints: 1
    victoryPoints: 4
    purchaseCost:
      SERVANTS: 2
      STONES: 2
  - developmentCardID: DEV_P5
    level: 2
    colour: PURPLE
    productions:
      - costs:
          resources:
            COINS: 1
          starResources: 0
        rewards:
          resources: { }
          starResources: 0
          faithPoints: 2
    victoryPoints: 5
    purchaseCost:
      SERVANTS: 4
  - developmentCardID: DEV_P6
    level: 2
    colour: PURPLE
    productions:
      - costs:
          resources:
            COINS: 1
            SERVANTS: 1
          starResources: 0
        rewards:
          resources:
            SHIELDS: 3
          starResources: 0
          faithPoints: 0
    victoryPoints: 6
    purchaseCost:
      SERVANTS: 3
      COINS: 2
  - developmentCardID: DEV_P7
    level: 2
    colour: PURPLE
    productions:
      - costs:
          resources:
            STONES: 2
          starResources: 0
        rewards:
          resources:
            COINS: 2
          starResources: 0
          faithPoints: 2
    victoryPoints: 7
    purchaseCost:
      SERVANTS: 5
  - developmentCardID: DEV_P8
    level: 2
    colour: PURPLE
    productions:
      - costs:
          resources:
            STONES: 1
          starResources: 0
        rewards:
          resources:
            SERVANTS: 2
          starResources: 0
          faithPoints: 1
    victoryPoints: 8
    purchaseCost:
      SERVANTS: 3
      SHIELDS: 3
  - developmentCardID: DEV_P9
    level: 3
    colour: PURPLE
    productions:
      - costs:
          resources:
            STONES: 2
          starResources: 0
        rewards:
          resources:
            COINS: 3
          starResources: 0
          faithPoints: 2
    victoryPoints: 9
    purchaseCost:
      SERVANTS: 6
  - developmentCardID: DEV_P10
    level: 3
    colour: PURPLE
    productions:
      - costs:
          resources:
            STONES: 1
            SHIELDS: 1
          starResources: 0
        rewards:
          resources:
            COINS: 2
            SERVANTS: 2
          starResources: 0
          faithPoints: 1
    victoryPoints: 10
    purchaseCost:
      SERVANTS: 5
      COINS: 2
  - developmentCardID: DEV_P11
    level: 3
    colour: PURPLE
    productions:
      - costs:
          resources:
            COINS: 1
          starResources: 0
        rewards:
          resources:
            STONES: 1
          starResources: 0
          faithPoints: 3
    victoryPoints: 11
    purchaseCost:
      SERVANTS: 7
  - developmentCardID: DEV_P12
    level: 3
    colour: PURPLE
    productions:
      - costs:
          resources:
            COINS: 1
          starResources: 0
        rewards:
          resources:
            SERVANTS: 1
            STONES: 3
          starResources: 0
          faithPoints: 0
    victoryPoints: 12
    purchaseCost:
      SERVANTS: 4
      SHIELDS: 4