# STANDARD RULES VALUES #

## FAITH PATH CONFIGURATION FILE ##
# This file sets all the parameters regarding the Faith Path.

# The Faith Path is characterized by the following aspects:
#  - length of the Faith Path
#  - information about Vatican Report Sections:
#    - position in which this section starts
#    - position of the Pope space, in which a Player triggers the Vatican Report
#    - number of Victory Points scored by a Player for the related Pope's Favor card turned face-up (active)
#  - number of Victory Points given at the end of the Game to the Player based on his position in the Faith Track
faithPathLength: 25
vaticanReportSections:
  - initialPosition: 5
    popeSpacePosition: 8
    victoryPoints: 2
  - initialPosition: 12
    popeSpacePosition: 16
    victoryPoints: 3
  - initialPosition: 19
    popeSpacePosition: 24
    victoryPoints: 4
victoryPointsByPosition:
  - startPosition: 0
    endPosition: 2
    victoryPoints: 0
  - startPosition: 3
    endPosition: 5
    victoryPoints: 1
  - startPosition: 6
    endPosition: 8
    victoryPoints: 2
  - startPosition: 9
    endPosition: 11
    victoryPoints: 4
  - startPosition: 12
    endPosition: 14
    victoryPoints: 6
  - startPosition: 15
    endPosition: 17
    victoryPoints: 9
  - startPosition: 18
    endPosition: 20
    victoryPoints: 12
  - startPosition: 21
    endPosition: 23
    victoryPoints: 16
  - startPosition: 24
    endPosition: 24
    victoryPoints: 20